# Generated by Django 6.0.4 on 2026-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='banner',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_license',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='id_card',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
