# Generated by Django 6.0.4 on 2026-04-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_order_device_type_orderitem_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='positive_feedback_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='response_rate_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='shipping_time',
            field=models.CharField(default='1-2 Days', max_length=100),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to='sellers.sellerprofile'),
        ),
    ]
