# Generated by Django 6.0.4 on 2026-04-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_order_customer_email_order_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cost_price',
            new_name='original',
        ),
        migrations.RemoveField(
            model_name='order',
            name='device_type',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
