# Generated by Django 6.0.4 on 2026-04-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='phone_number',
            field=models.CharField(default='08132106194'),
        ),
    ]
