# Generated by Django 6.0.4 on 2026-06-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0011_sellerprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
