# Generated by Django 6.0.4 on 2026-06-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0012_product_image2_product_image3_product_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='phone_number',
            field=models.CharField(default='08132106194', max_length=15),
        ),
    ]
