# Generated by Django 6.0.4 on 2026-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('FUNDING', 'Wallet Funding'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund'), ('WITHDRAWAL', 'Withdrawal'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('REFERRAL_REWARD', 'Referral Reward')], max_length=20),
        ),
    ]
